config/routes.rb
Rouge::Application.routes.draw do
  resources :reviews

  resources :reviewers

  resources :restaurants

  resources :administrators

  root :to => "guide#index"
  match 'guide/:action/:id' => 'guide'

end

app/models/reviewer.rb
class Reviewer < ActiveRecord::Base
  has_many :reviews
end

app/controllers/reviewers_controller.rb
class ReviewersController < AuthenticatedController
  layout 'authenticated'
  
  # GET /reviewers
  # GET /reviewers.xml
  def index
    @reviewers = Reviewer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @reviewers }
    end
  end

  # GET /reviewers/1
  # GET /reviewers/1.xml
  def show
    @reviewer = Reviewer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @reviewer }
    end
  end

  # GET /reviewers/new
  # GET /reviewers/new.xml
  def new
    @reviewer = Reviewer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @reviewer }
    end
  end

  # GET /reviewers/1/edit
  def edit
    @reviewer = Reviewer.find(params[:id])
  end

  # POST /reviewers
  # POST /reviewers.xml
  def create
    @reviewer = Reviewer.new(params[:reviewer])

    respond_to do |format|
      if @reviewer.save
        format.html { redirect_to(@reviewer, :notice => 'Reviewer was successfully created.') }
        format.xml  { render :xml => @reviewer, :status => :created, :location => @reviewer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @reviewer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reviewers/1
  # PUT /reviewers/1.xml
  def update
    @reviewer = Reviewer.find(params[:id])

    respond_to do |format|
      if @reviewer.update_attributes(params[:reviewer])
        format.html { redirect_to(@reviewer, :notice => 'Reviewer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @reviewer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reviewers/1
  # DELETE /reviewers/1.xml
  def destroy
    @reviewer = Reviewer.find(params[:id])
    @reviewer.destroy

    respond_to do |format|
      format.html { redirect_to(reviewers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/reviewers_helper.rb
module ReviewersHelper
end

app/views/reviewers/_form.html.erb
<%= form_for(@reviewer) do |f| %>
  <% if @reviewer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reviewer.errors.count, "error") %> prohibited this reviewer from being saved:</h2>

      <ul>
      <% @reviewer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviewers/edit.html.erb
<h1>Editing reviewer</h1>

<%= render 'form' %>

<%= link_to 'Show', @reviewer %> |
<%= link_to 'Back', reviewers_path %>

app/views/reviewers/index.html.erb
<h1>Listing reviewers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviewers.each do |reviewer| %>
  <tr>
    <td><%= reviewer.name %></td>
    <td><%= reviewer.description %></td>
    <td><%= reviewer.username %></td>
    <td><%= reviewer.password.gsub(/./, '*') %></td>
    <td><%= link_to 'Show', reviewer %></td>
    <td><%= link_to 'Edit', edit_reviewer_path(reviewer) %></td>
    <td><%= link_to 'Destroy', reviewer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reviewer', new_reviewer_path %>

app/views/reviewers/new.html.erb
<h1>New reviewer</h1>

<%= render 'form' %>

<%= link_to 'Back', reviewers_path %>

app/views/reviewers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @reviewer.name %>
</p>

<p>
  <b>Description:</b>
  <%= @reviewer.description %>
</p>

<p>
  <b>Username:</b>
  <%= @reviewer.username %>
</p>

<p>
  <b>Password:</b>
  <%= @reviewer.password.gsub(/./, '*') %>
</p>


<%= link_to 'Edit', edit_reviewer_path(@reviewer) %> |
<%= link_to 'Back', reviewers_path %>