config/routes.rb
Rouge::Application.routes.draw do
  resources :reviews

  resources :reviewers

  resources :restaurants

  resources :administrators

  root :to => "guide#index"
  match 'guide/:action/:id' => 'guide'

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
end

app/controllers/administrators_controller.rb
class AdministratorsController < AuthenticatedController
  layout 'authenticated'
  # GET /administrators
  # GET /administrators.xml
  def index
    @administrators = Administrator.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @administrators }
    end
  end

  # GET /administrators/1
  # GET /administrators/1.xml
  def show
    @administrator = Administrator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @administrator }
    end
  end

  # GET /administrators/new
  # GET /administrators/new.xml
  def new
    @administrator = Administrator.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @administrator }
    end
  end

  # GET /administrators/1/edit
  def edit
    @administrator = Administrator.find(params[:id])
  end

  # POST /administrators
  # POST /administrators.xml
  def create
    @administrator = Administrator.new(params[:administrator])

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to(@administrator, :notice => 'Administrator was successfully created.') }
        format.xml  { render :xml => @administrator, :status => :created, :location => @administrator }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @administrator.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /administrators/1
  # PUT /administrators/1.xml
  def update
    @administrator = Administrator.find(params[:id])

    respond_to do |format|
      if @administrator.update_attributes(params[:administrator])
        format.html { redirect_to(@administrator, :notice => 'Administrator was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @administrator.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.xml
  def destroy
    @administrator = Administrator.find(params[:id])
    @administrator.destroy

    respond_to do |format|
      format.html { redirect_to(administrators_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.erb
<%= form_for(@administrator) do |f| %>
  <% if @administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
      <% @administrator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<h1>Editing administrator</h1>

<%= render 'form' %>

<%= link_to 'Show', @administrator %> |
<%= link_to 'Back', administrators_path %>

app/views/administrators/index.html.erb
<h1>Listing administrators</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @administrators.each do |administrator| %>
  <tr>
    <td><%= administrator.username %></td>
    <td><%= administrator.password.gsub(/./, '*') %></td>
    <td><%= link_to 'Show', administrator %></td>
    <td><%= link_to 'Edit', edit_administrator_path(administrator) %></td>
    <td><%= link_to 'Destroy', administrator, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Administrator', new_administrator_path %>

app/views/administrators/new.html.erb
<h1>New administrator</h1>

<%= render 'form' %>

<%= link_to 'Back', administrators_path %>

app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @administrator.username %>
</p>

<p>
  <b>Password:</b>
  <%= @administrator.password.gsub(/./, '*') %>
</p>


<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>